steps:
    - id: get-secret
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
          [
              '-c',
              "gcloud secrets versions access latest --secret=$_SECRET --format='get(payload.data)' | tr '_-' '/+' | base64 -d | sed 's/^/export /' > /workspace/secrets.env",
          ]

    - id: install-deps
      name: 'node:18'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              source /workspace/secrets.env
              npm install

    - id: build
      name: 'node:18'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              source /workspace/secrets.env
              npm run build

    - id: docker-build
      name: 'gcr.io/cloud-builders/docker'
      args:
          - 'build'
          - '--target'
          - 'production'
          - '-t'
          - '$_AR_HOSTNAME/$_PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'
          - '--build-arg'
          - 'REACT_APP_BASE_URL=$_REACT_APP_BASE_URL'
          - './'

    - id: push
      name: 'gcr.io/cloud-builders/docker'
      args:
          - 'push'
          - '$_AR_HOSTNAME/$_PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'

    - id: deploy
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args:
          - 'run'
          - 'deploy'
          - '$_SERVICE_NAME'
          - '--image'
          - '$_AR_HOSTNAME/$_PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'
          - '--region'
          - '$_DEPLOY_REGION'
          - '--project'
          - '$_PROJECT_ID'
options:
    logging: CLOUD_LOGGING_ONLY

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
            args:
                - REACT_APP_API_URL=${REACT_APP_API_URL}
        container_name: ${DOCKER_SERVICE_NAME}
        volumes:
            - ./src:/app/src
            - ./node_modules:/app/node_modules
            - ./package.json:/app/package.json
            - ./package-lock.json:/app/package-lock.json
            - ./tsconfig.json:/app/tsconfig.json
            - ./nodemon.json:/app/nodemon.json
            # - ./service-account.json:/app/service-account.json
        ports:
            - '${DOCKER_PORT}:8080'
            - '9229:9229'
        networks:
            - backend
        env_file: .env
        restart: unless-stopped

networks:
    backend:
        external: true
        name: prueba
